run num.1000.1.in:
	@echo " "
	
	@python main.py instancias-num\num.1000.1.in 
	@echo " "

run num.1000.2.in:
	@echo " "
	
	@python main.py instancias-num\num.1000.2.in 
	@echo " "

run num.1000.3.in:
	@echo " "
	
	@python main.py instancias-num\num.1000.3.in 
	@echo " "

run num.1000.4.in:
	@echo " "
	
	@python main.py instancias-num\num.1000.4.in 
	@echo " "

run num.10000.1.in:
	@echo " "
	
	@python main.py instancias-num\num.10000.1.in 
	@echo " "

run num.10000.2.in:
	@echo " "
	
	@python main.py instancias-num\num.10000.2.in 
	@echo " "

run num.10000.3.in:
	@echo " "
	
	@python main.py instancias-num\num.10000.3.in 
	@echo " "

run num.10000.4.in:
	@echo " "
	
	@python main.py instancias-num\num.10000.4.in 
	@echo " "

run num.100000.1.in:
	@echo " "
	
	@python main.py instancias-num\num.100000.1.in 
	@echo " "

run num.100000.2.in:
	@echo " "
	
	@python main.py instancias-num\num.100000.2.in 
	@echo " "

run num.100000.3.in:
	@echo " "
	
	@python main.py instancias-num\num.100000.3.in 
	@echo " "

run num.100000.4.in:
	@echo " "
	
	@python main.py instancias-num\num.100000.4.in 
	@echo " "
